### ISSUE TITLE
[strands_tweets] Other communication styles for strands_tweets

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_utils#39] opened 2013-11-21 13:31 UTC
Due to networking issues here (or at least I think so), occasionally calls to the Tweet service block for a long time without returning (as the tweet.py node tries then times out when connecting to our proxy). This in turn blocks the calling node, potentially causing issues.

To overcome this it would be great if tweet.py could offer a topic to receive tweets on (as it's not super-critical if they're received) or alternatively over an actionlib interface (and thus supporting a timeout).

**Comment by Jailander** [comment] 2013-11-21 13:53
Ok, I will implement it as an action server (which was my original idea) with a timeout.

**Comment by Jailander** [comment] 2013-11-22 14:31
Hi I already Implemented an action server for this, the service can be used too, how ever it doesn't have a timeout yet, this will be added soon.

**Comment by cdondrup** [comment] 2014-09-04 15:39
I guess the timeout can just be added when calling the action server, e.g.:

```
client.wait_for_result(rospy.Duration.from_sec(5.0))
```

Imho this means you (@Jailander) don't have to implement anything as long as the preempt callback is working as intended. Therefore I would close this issue if no one objects.

**Comment by Jailander** [comment] 2014-09-04 16:24
I know, I meant a timeout for the service, so other people don't have to change their code, still haven't done it though

**Closed as completed** 2014-11-11 21:44 UTC
Labels: enhancement
